/* gmpc_menu_item_rating.vapi generated by valac, do not modify. */

[CCode (cprefix = "Gmpc", lower_case_cprefix = "gmpc_")]
namespace Gmpc {
	[CCode (cprefix = "GmpcMenuItem", lower_case_cprefix = "gmpc_menu_item_")]
	namespace MenuItem {
		[CCode (cheader_filename = "gmpc_menu_item_rating.h")]
		public class Rating : Gtk.MenuItem {
			public Gtk.VBox hbox;
			public Gmpc.Rating rating;
			public Rating (MPD.Server server, MPD.Song song);
			public int get_rating ();
		}
	}
}
