/* gmpc-nowplaying2.h generated by valac, the Vala compiler, do not modify */


#ifndef __GMPC_NOWPLAYING2_H__
#define __GMPC_NOWPLAYING2_H__

#include <glib.h>
#include <gmpc-plugin.h>

G_BEGIN_DECLS


#define GMPC_PLUGIN_TYPE_MOCKUP (gmpc_plugin_mockup_get_type ())
#define GMPC_PLUGIN_MOCKUP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GMPC_PLUGIN_TYPE_MOCKUP, GmpcPluginMockup))
#define GMPC_PLUGIN_MOCKUP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GMPC_PLUGIN_TYPE_MOCKUP, GmpcPluginMockupClass))
#define GMPC_PLUGIN_IS_MOCKUP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GMPC_PLUGIN_TYPE_MOCKUP))
#define GMPC_PLUGIN_IS_MOCKUP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GMPC_PLUGIN_TYPE_MOCKUP))
#define GMPC_PLUGIN_MOCKUP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GMPC_PLUGIN_TYPE_MOCKUP, GmpcPluginMockupClass))

typedef struct _GmpcPluginMockup GmpcPluginMockup;
typedef struct _GmpcPluginMockupClass GmpcPluginMockupClass;
typedef struct _GmpcPluginMockupPrivate GmpcPluginMockupPrivate;

struct _GmpcPluginMockup {
	GmpcPluginBase parent_instance;
	GmpcPluginMockupPrivate * priv;
};

struct _GmpcPluginMockupClass {
	GmpcPluginBaseClass parent_class;
};


GType gmpc_plugin_mockup_get_type (void);
GmpcPluginMockup* gmpc_plugin_mockup_new (void);
GmpcPluginMockup* gmpc_plugin_mockup_construct (GType object_type);

static const gint GMPC_PLUGIN_MOCKUP_version[] = {0, 0, 0};

G_END_DECLS

#endif
