/* gmpc-liststore-sort.vapi generated by valac, do not modify. */

[CCode (cprefix = "Gmpc", lower_case_cprefix = "gmpc_")]
namespace Gmpc {
	[CCode (cprefix = "GmpcListstore", lower_case_cprefix = "gmpc_liststore_")]
	namespace Liststore {
		[CCode (cheader_filename = "gmpc-liststore-sort.h")]
		public class Sort : Gtk.ListStore, Gtk.TreeDragSource, Gtk.TreeDragDest {
			public Sort ();
		}
	}
}
