/* gmpc-paned-size-group.vapi generated by valac, do not modify. */

[CCode (cprefix = "Gmpc", lower_case_cprefix = "gmpc_")]
namespace Gmpc {
	[CCode (cheader_filename = "gmpc-paned-size-group.h")]
	public class PanedSizeGroup : GLib.Object {
		public void add_paned (Gtk.Paned paned);
		public PanedSizeGroup ();
	}
}
