/* gmpc-favorites.vapi generated by valac, do not modify. */

[CCode (cprefix = "Gmpc", lower_case_cprefix = "gmpc_")]
namespace Gmpc {
	[CCode (cprefix = "GmpcFavorites", lower_case_cprefix = "gmpc_favorites_")]
	namespace Favorites {
		[CCode (cheader_filename = "gmpc-favorites.h")]
		public class Button : Gtk.EventBox {
			public Button ();
			public void set_song (MPD.Song? song);
		}
	}
}
