/* gmpc-image.vapi generated by valac, do not modify. */

[CCode (cprefix = "Gmpc", lower_case_cprefix = "gmpc_")]
namespace Gmpc {
	[CCode (cheader_filename = "gmpc-image.h")]
	public class Image : Gtk.EventBox {
		public Image ();
		public void clear_pixbuf ();
		public void set_pixbuf (Gdk.Pixbuf buf, bool border);
		public string? text { get; set; }
	}
}
