/* gmpc-rating.vapi generated by valac, do not modify. */

[CCode (cprefix = "Gmpc", lower_case_cprefix = "gmpc_")]
namespace Gmpc {
	[CCode (cheader_filename = "gmpc-rating.h")]
	public class Rating : Gtk.Frame {
		public Gtk.EventBox event_box;
		public bool button_press_event_callback (Gtk.EventBox wid, Gdk.EventButton event);
		public Rating (MPD.Server server, MPD.Song song);
		public void set_rating (int rating);
		public void update ();
	}
}
