
.TH gmpc 1 "October 29, 2008" "" "Gnome Music Player Client - Remote control"

.SH NAME
gmpc-remote [OPTION]

.SH DESCRIPTION
If gmpc is compiled with IPC support gmpc-remote can send commands to the running instance of gmpc.

.SH OPTIONS
.TP
.BI --version
Display version.
.TP
.BI --quit -q 
Quit the running gmpc.
.TP
.BI --play -c 
Give GMPC the play command.
.TP
.BI --pause -v
Give GMPC the pause command.
.TP
.BI --next -b
Give GMPC the next command.
.TP
.BI --prev -z
Give GMPC the previous command.
.TP
.BI --stop -x
Give GMPC the stop command.
.TP
.BI --stream -s
Gives mpd a stream to parse and play.
.br

.SH SEE ALSO
Website: http://gmpcwiki.sarine.nl

MPD Website: http://www.musicpd.org

.SH AUTHOR
gmpc-remote was written by Qball Cow <qball@sarine.nl>
