
.TH gmpc-remote-stream 1 "May 30, 2011" "" "Gnome Music Player Client - Remote control"

.SH NAME
gmpc-remote-stream - a remote control for GMPC.

.SH SYNOPSIS
gmpc-remote-stream [OPTION]

.SH DESCRIPTION
If gmpc is compiled with IPC support gmpc-remote can send commands to the
running instance of gmpc.  gmpc-remote-stream is a wrapper around gmpc-remote
that will pass it the extra option \-\-stream.

.SH SEE ALSO
.BR gmpc-remote(1)

.SH AUTHOR
This manual page was written by Etienne Millon <etienne.millon@gmail.com>
