/* Generated by GOB (v2.0.14)   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 14

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "gmpc-metaimage.h"

#include "gmpc-metaimage-private.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */
/* self casting macros */
#define SELF(x) GMPC_METAIMAGE(x)
#define SELF_CONST(x) GMPC_METAIMAGE_CONST(x)
#define IS_SELF(x) GMPC_IS_METAIMAGE(x)
#define TYPE_SELF GMPC_TYPE_METAIMAGE
#define SELF_CLASS(x) GMPC_METAIMAGE_CLASS(x)

#define SELF_GET_CLASS(x) GMPC_METAIMAGE_GET_CLASS(x)

/* self typedefs */
typedef GmpcMetaImage Self;
typedef GmpcMetaImageClass SelfClass;

/* here are local prototypes */
static void ___object_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec);
static void ___object_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec);
static void gmpc_metaimage_class_init (GmpcMetaImageClass * c) G_GNUC_UNUSED;
static void gmpc_metaimage_init (GmpcMetaImage * self) G_GNUC_UNUSED;
static void ___6_gmpc_metaimage_finalize (GmpcMetaImage * self) G_GNUC_UNUSED;
static void gmpc_metaimage_update_cover (GmpcMetaImage * self, MpdObj * mi, ChangedStatusType what, GmpcConnection * gmpcconn) G_GNUC_UNUSED;
static void gmpc_metaimage_meta_callback (mpd_Song * song, MetaDataResult ret, char * path, GmpcMetaImage * self) G_GNUC_UNUSED;

enum {
	PROP_0,
	PROP_IMAGE_TYPE,
	PROP_SIZE
};

/* pointer to the class of our parent */
static GtkEventBoxClass *parent_class = NULL;

/* Short form macros */
#define self_get_image_type gmpc_metaimage_get_image_type
#define self_set_image_type gmpc_metaimage_set_image_type
#define self_get_size gmpc_metaimage_get_size
#define self_set_size gmpc_metaimage_set_size
#define self_new gmpc_metaimage_new
#define self_update_cover gmpc_metaimage_update_cover
#define self_meta_callback gmpc_metaimage_meta_callback
#define self_set_cover_na gmpc_metaimage_set_cover_na
#define self_set_cover_fetching gmpc_metaimage_set_cover_fetching
#define self_set_cover_from_path gmpc_metaimage_set_cover_from_path
GType
gmpc_metaimage_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (GmpcMetaImageClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) gmpc_metaimage_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (GmpcMetaImage),
			0 /* n_preallocs */,
			(GInstanceInitFunc) gmpc_metaimage_init,
			NULL
		};

		type = g_type_register_static (GTK_TYPE_EVENT_BOX, "GmpcMetaImage", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((GmpcMetaImage *)g_object_new(gmpc_metaimage_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static GmpcMetaImage * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static GmpcMetaImage *
GET_NEW_VARG (const char *first, ...)
{
	GmpcMetaImage *ret;
	va_list ap;
	va_start (ap, first);
	ret = (GmpcMetaImage *)g_object_new_valist (gmpc_metaimage_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "Gmpc:MetaImage::finalize"
	GmpcMetaImage *self G_GNUC_UNUSED = GMPC_METAIMAGE (obj_self);
	gpointer priv G_GNUC_UNUSED = self->_priv;
#line 41 "cover-image.gob"
	___6_gmpc_metaimage_finalize(obj_self);
#line 118 "gmpc-metaimage.c"
#line 30 "cover-image.gob"
	if(self->_priv->image) { gtk_widget_destroy ((gpointer) self->_priv->image); self->_priv->image = NULL; }
#line 121 "gmpc-metaimage.c"
}
#undef __GOB_FUNCTION__

static void 
gmpc_metaimage_class_init (GmpcMetaImageClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Gmpc:MetaImage::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	g_type_class_add_private(c,sizeof(GmpcMetaImagePrivate));

	parent_class = g_type_class_ref (GTK_TYPE_EVENT_BOX);

#line 41 "cover-image.gob"
	g_object_class->finalize = ___finalize;
#line 137 "gmpc-metaimage.c"
	g_object_class->get_property = ___object_get_property;
	g_object_class->set_property = ___object_set_property;
    {
	GParamSpec   *param_spec;

	param_spec = g_param_spec_int
		("image_type" /* name */,
		 _("Image type") /* nick */,
		 _("Type of the image, like artist art") /* blurb */,
		 G_MININT /* minimum */,
		 G_MAXINT /* maximum */,
		 META_ALBUM_ART /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_IMAGE_TYPE,
		param_spec);
	param_spec = g_param_spec_int
		("size" /* name */,
		 _("Size") /* nick */,
		 _("Size of the image") /* blurb */,
		 G_MININT /* minimum */,
		 G_MAXINT /* maximum */,
		 64 /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_SIZE,
		param_spec);
    }
}
#undef __GOB_FUNCTION__
#line 31 "cover-image.gob"
static void 
gmpc_metaimage_init (GmpcMetaImage * self G_GNUC_UNUSED)
#line 171 "gmpc-metaimage.c"
{
#define __GOB_FUNCTION__ "Gmpc:MetaImage::init"
	self->_priv = G_TYPE_INSTANCE_GET_PRIVATE(self,GMPC_TYPE_METAIMAGE,GmpcMetaImagePrivate);
#line 11 "cover-image.gob"
	self->size = 64;
#line 177 "gmpc-metaimage.c"
#line 12 "cover-image.gob"
	self->_priv->status_signal = 0;
#line 180 "gmpc-metaimage.c"
#line 13 "cover-image.gob"
	self->image_type = META_ALBUM_ART;
#line 183 "gmpc-metaimage.c"
#line 29 "cover-image.gob"
	self->_priv->image =  gtk_image_new();
#line 186 "gmpc-metaimage.c"
 {
#line 32 "cover-image.gob"

		/** Set size */
		gtk_container_add(GTK_CONTAINER(self), self->_priv->image);		
		self_set_cover_na(self);
		gtk_widget_show_all(self);
		self->_priv->status_signal = g_signal_connect_swapped(G_OBJECT(gmpcconn), "status_changed",
				self_update_cover, self);
	
#line 197 "gmpc-metaimage.c"
 }
}
#undef __GOB_FUNCTION__

static void
___object_set_property (GObject *object,
	guint property_id,
	const GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "Gmpc:MetaImage::set_property"
{
	GmpcMetaImage *self G_GNUC_UNUSED;

	self = GMPC_METAIMAGE (object);

	switch (property_id) {
	case PROP_IMAGE_TYPE:
		{
#line 15 "cover-image.gob"
self->image_type = g_value_get_int (VAL);
#line 218 "gmpc-metaimage.c"
		}
		break;
	case PROP_SIZE:
		{
#line 22 "cover-image.gob"
self->size = g_value_get_int (VAL);
#line 225 "gmpc-metaimage.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__

static void
___object_get_property (GObject *object,
	guint property_id,
	GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "Gmpc:MetaImage::get_property"
{
	GmpcMetaImage *self G_GNUC_UNUSED;

	self = GMPC_METAIMAGE (object);

	switch (property_id) {
	case PROP_IMAGE_TYPE:
		{
#line 15 "cover-image.gob"
g_value_set_int (VAL, self->image_type);
#line 256 "gmpc-metaimage.c"
		}
		break;
	case PROP_SIZE:
		{
#line 22 "cover-image.gob"
g_value_set_int (VAL, self->size);
#line 263 "gmpc-metaimage.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__


#line 15 "cover-image.gob"
gint 
gmpc_metaimage_get_image_type (GmpcMetaImage * self)
#line 282 "gmpc-metaimage.c"
{
#define __GOB_FUNCTION__ "Gmpc:MetaImage::get_image_type"
{
#line 15 "cover-image.gob"
		gint val; g_object_get (G_OBJECT (self), "image_type", &val, NULL); return val;
}}
#line 289 "gmpc-metaimage.c"
#undef __GOB_FUNCTION__

#line 15 "cover-image.gob"
void 
gmpc_metaimage_set_image_type (GmpcMetaImage * self, gint val)
#line 295 "gmpc-metaimage.c"
{
#define __GOB_FUNCTION__ "Gmpc:MetaImage::set_image_type"
{
#line 15 "cover-image.gob"
		g_object_set (G_OBJECT (self), "image_type", val, NULL);
}}
#line 302 "gmpc-metaimage.c"
#undef __GOB_FUNCTION__

#line 22 "cover-image.gob"
gint 
gmpc_metaimage_get_size (GmpcMetaImage * self)
#line 308 "gmpc-metaimage.c"
{
#define __GOB_FUNCTION__ "Gmpc:MetaImage::get_size"
{
#line 22 "cover-image.gob"
		gint val; g_object_get (G_OBJECT (self), "size", &val, NULL); return val;
}}
#line 315 "gmpc-metaimage.c"
#undef __GOB_FUNCTION__

#line 22 "cover-image.gob"
void 
gmpc_metaimage_set_size (GmpcMetaImage * self, gint val)
#line 321 "gmpc-metaimage.c"
{
#define __GOB_FUNCTION__ "Gmpc:MetaImage::set_size"
{
#line 22 "cover-image.gob"
		g_object_set (G_OBJECT (self), "size", val, NULL);
}}
#line 328 "gmpc-metaimage.c"
#undef __GOB_FUNCTION__


#line 41 "cover-image.gob"
static void 
___6_gmpc_metaimage_finalize (GmpcMetaImage * self G_GNUC_UNUSED)
#line 335 "gmpc-metaimage.c"
#define PARENT_HANDLER(___self) \
	{ if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(___self); }
{
#define __GOB_FUNCTION__ "Gmpc:MetaImage::finalize"
#line 41 "cover-image.gob"
	g_return_if_fail (self != NULL);
#line 41 "cover-image.gob"
	g_return_if_fail (GMPC_IS_METAIMAGE (self));
#line 345 "gmpc-metaimage.c"
{
#line 44 "cover-image.gob"
	
		printf("Finalizing metaimage\n");
		if(self->_priv->status_signal)
		{
			g_signal_handler_disconnect(G_OBJECT(gmpcconn), self->_priv->status_signal);
		}

	}}
#line 356 "gmpc-metaimage.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 53 "cover-image.gob"
GtkWidget * 
gmpc_metaimage_new (int type)
#line 363 "gmpc-metaimage.c"
{
#define __GOB_FUNCTION__ "Gmpc:MetaImage::new"
{
#line 55 "cover-image.gob"
	
		Self *gmi =  GET_NEW;
		gmi->image_type = type;
		return (GtkWidget *)gmi;
	}}
#line 373 "gmpc-metaimage.c"
#undef __GOB_FUNCTION__

#line 61 "cover-image.gob"
static void 
gmpc_metaimage_update_cover (GmpcMetaImage * self, MpdObj * mi, ChangedStatusType what, GmpcConnection * gmpcconn)
#line 379 "gmpc-metaimage.c"
{
#define __GOB_FUNCTION__ "Gmpc:MetaImage::update_cover"
#line 61 "cover-image.gob"
	g_return_if_fail (self != NULL);
#line 61 "cover-image.gob"
	g_return_if_fail (GMPC_IS_METAIMAGE (self));
#line 386 "gmpc-metaimage.c"
{
#line 64 "cover-image.gob"
	
		if(what&(MPD_CST_SONGID|MPD_CST_SONGPOS))
		{
			mpd_Song *song = mpd_playlist_get_current_song(mi);
			if(!song)
			{
				self_set_cover_na(self);
			}
			else
			{
				meta_data_get_path_callback(song, self->image_type, self_meta_callback, self);
			}
		}

	}}
#line 404 "gmpc-metaimage.c"
#undef __GOB_FUNCTION__

#line 79 "cover-image.gob"
static void 
gmpc_metaimage_meta_callback (mpd_Song * song, MetaDataResult ret, char * path, GmpcMetaImage * self)
#line 410 "gmpc-metaimage.c"
{
#define __GOB_FUNCTION__ "Gmpc:MetaImage::meta_callback"
{
#line 82 "cover-image.gob"
	
		mpd_Song *current = mpd_playlist_get_current_song(connection);
		if(!current)
			return;
		if(!strcmp(song->file, current->file))
		{
			if(ret == META_DATA_AVAILABLE)
			{
				self_set_cover_from_path(self,path); 
			}
			else if (ret == META_DATA_FETCHING)
			{
				self_set_cover_fetching(self);
			}
			else
			{
				self_set_cover_na(self);
			}
		}

	}}
#line 436 "gmpc-metaimage.c"
#undef __GOB_FUNCTION__

#line 105 "cover-image.gob"
void 
gmpc_metaimage_set_cover_na (GmpcMetaImage * self)
#line 442 "gmpc-metaimage.c"
{
#define __GOB_FUNCTION__ "Gmpc:MetaImage::set_cover_na"
#line 105 "cover-image.gob"
	g_return_if_fail (self != NULL);
#line 105 "cover-image.gob"
	g_return_if_fail (GMPC_IS_METAIMAGE (self));
#line 449 "gmpc-metaimage.c"
{
#line 108 "cover-image.gob"
	
		gtk_image_set_from_stock(self->_priv->image, "media-no-cover", -1);
	}}
#line 455 "gmpc-metaimage.c"
#undef __GOB_FUNCTION__

#line 111 "cover-image.gob"
void 
gmpc_metaimage_set_cover_fetching (GmpcMetaImage * self)
#line 461 "gmpc-metaimage.c"
{
#define __GOB_FUNCTION__ "Gmpc:MetaImage::set_cover_fetching"
#line 111 "cover-image.gob"
	g_return_if_fail (self != NULL);
#line 111 "cover-image.gob"
	g_return_if_fail (GMPC_IS_METAIMAGE (self));
#line 468 "gmpc-metaimage.c"
{
#line 114 "cover-image.gob"
	
		gtk_image_set_from_stock(self->_priv->image, "media-loading-cover", -1);
	}}
#line 474 "gmpc-metaimage.c"
#undef __GOB_FUNCTION__

#line 117 "cover-image.gob"
void 
gmpc_metaimage_set_cover_from_path (GmpcMetaImage * self, gchar * path)
#line 480 "gmpc-metaimage.c"
{
#define __GOB_FUNCTION__ "Gmpc:MetaImage::set_cover_from_path"
#line 117 "cover-image.gob"
	g_return_if_fail (self != NULL);
#line 117 "cover-image.gob"
	g_return_if_fail (GMPC_IS_METAIMAGE (self));
#line 487 "gmpc-metaimage.c"
{
#line 120 "cover-image.gob"
	
		GdkPixbuf *pb = NULL;
		pb = gdk_pixbuf_new_from_file_at_scale(path,self->size,self->size,TRUE,NULL);
		if(pb)
		{
			draw_pixbuf_border(pb);
			gtk_image_set_from_pixbuf(GTK_IMAGE(self->_priv->image),pb);
			g_object_unref(pb);
		}
	}}
#line 500 "gmpc-metaimage.c"
#undef __GOB_FUNCTION__
