/* Generated by GOB (v2.0.14)   (do not edit directly) */

#include <glib.h>
#include <glib-object.h>


	#include <stdio.h>
	#include <libmpd/libmpd.h>
	#include <libmpd/debug_printf.h>

#ifndef __GMPC_CONNECTION_H__
#define __GMPC_CONNECTION_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/*
 * Type checking and casting macros
 */
#define GMPC_TYPE_CONNECTION	(gmpc_connection_get_type())
#define GMPC_CONNECTION(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), gmpc_connection_get_type(), GmpcConnection)
#define GMPC_CONNECTION_CONST(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), gmpc_connection_get_type(), GmpcConnection const)
#define GMPC_CONNECTION_CLASS(klass)	G_TYPE_CHECK_CLASS_CAST((klass), gmpc_connection_get_type(), GmpcConnectionClass)
#define GMPC_IS_CONNECTION(obj)	G_TYPE_CHECK_INSTANCE_TYPE((obj), gmpc_connection_get_type ())

#define GMPC_CONNECTION_GET_CLASS(obj)	G_TYPE_INSTANCE_GET_CLASS((obj), gmpc_connection_get_type(), GmpcConnectionClass)

/*
 * Main object structure
 */
#ifndef __TYPEDEF_GMPC_CONNECTION__
#define __TYPEDEF_GMPC_CONNECTION__
typedef struct _GmpcConnection GmpcConnection;
#endif
struct _GmpcConnection {
	GObject __parent__;
};

/*
 * Class definition
 */
typedef struct _GmpcConnectionClass GmpcConnectionClass;
struct _GmpcConnectionClass {
	GObjectClass __parent__;
	/*signal*/void (* connection_changed) (GmpcConnection * self, MpdObj * mi, int connect);
	/*signal*/void (* status_changed) (GmpcConnection * self, MpdObj * mi, ChangedStatusType what);
};


/*
 * Public methods
 */
GType	gmpc_connection_get_type	(void);
void 	gmpc_connection_connection_changed	(GmpcConnection * self,
					MpdObj * mi,
					int connect);
void 	gmpc_connection_status_changed	(GmpcConnection * self,
					MpdObj * mi,
					ChangedStatusType what);
GObject * 	gmpc_connection_new	(void);

/*
 * Signal connection wrapper macros
 */
#if defined(__GNUC__) && !defined(__STRICT_ANSI__)
#define gmpc_connection_connect__connection_changed(object,func,data)	g_signal_connect(GMPC_CONNECTION(__extension__ ({GmpcConnection *___object = (object); ___object; })),"connection_changed",(GCallback) __extension__ ({void (* ___connection_changed) (GmpcConnection * ___fake___self, MpdObj * ___fake___mi, int ___fake___connect, gpointer ___data ) = (func); ___connection_changed; }), (data))
#define gmpc_connection_connect_after__connection_changed(object,func,data)	g_signal_connect_after(GMPC_CONNECTION(__extension__ ({GmpcConnection *___object = (object); ___object; })),"connection_changed",(GCallback) __extension__ ({void (* ___connection_changed) (GmpcConnection * ___fake___self, MpdObj * ___fake___mi, int ___fake___connect, gpointer ___data ) = (func); ___connection_changed; }), (data))
#define gmpc_connection_connect_data__connection_changed(object,func,data,destroy_data,flags)	g_signal_connect_data(GMPC_CONNECTION(__extension__ ({GmpcConnection *___object = (object); ___object; })),"connection_changed",(GCallback) __extension__ ({void (* ___connection_changed) (GmpcConnection * ___fake___self, MpdObj * ___fake___mi, int ___fake___connect, gpointer ___data ) = (func); ___connection_changed; }), (data), (destroy_data), (GConnectFlags)(flags))
#define gmpc_connection_connect__status_changed(object,func,data)	g_signal_connect(GMPC_CONNECTION(__extension__ ({GmpcConnection *___object = (object); ___object; })),"status_changed",(GCallback) __extension__ ({void (* ___status_changed) (GmpcConnection * ___fake___self, MpdObj * ___fake___mi, ChangedStatusType ___fake___what, gpointer ___data ) = (func); ___status_changed; }), (data))
#define gmpc_connection_connect_after__status_changed(object,func,data)	g_signal_connect_after(GMPC_CONNECTION(__extension__ ({GmpcConnection *___object = (object); ___object; })),"status_changed",(GCallback) __extension__ ({void (* ___status_changed) (GmpcConnection * ___fake___self, MpdObj * ___fake___mi, ChangedStatusType ___fake___what, gpointer ___data ) = (func); ___status_changed; }), (data))
#define gmpc_connection_connect_data__status_changed(object,func,data,destroy_data,flags)	g_signal_connect_data(GMPC_CONNECTION(__extension__ ({GmpcConnection *___object = (object); ___object; })),"status_changed",(GCallback) __extension__ ({void (* ___status_changed) (GmpcConnection * ___fake___self, MpdObj * ___fake___mi, ChangedStatusType ___fake___what, gpointer ___data ) = (func); ___status_changed; }), (data), (destroy_data), (GConnectFlags)(flags))
#else /* __GNUC__ && !__STRICT_ANSI__ */
#define gmpc_connection_connect__connection_changed(object,func,data)	g_signal_connect(GMPC_CONNECTION(object),"connection_changed",(GCallback)(func),(data))
#define gmpc_connection_connect_after__connection_changed(object,func,data)	g_signal_connect_after(GMPC_CONNECTION(object),"connection_changed",(GCallback)(func),(data))
#define gmpc_connection_connect_data__connection_changed(object,func,data,destroy_data,flags)	g_signal_connect_data(GMPC_CONNECTION(object),"connection_changed",(GCallback)(func),(data),(destroy_data),(GConnectFlags)(flags))
#define gmpc_connection_connect__status_changed(object,func,data)	g_signal_connect(GMPC_CONNECTION(object),"status_changed",(GCallback)(func),(data))
#define gmpc_connection_connect_after__status_changed(object,func,data)	g_signal_connect_after(GMPC_CONNECTION(object),"status_changed",(GCallback)(func),(data))
#define gmpc_connection_connect_data__status_changed(object,func,data,destroy_data,flags)	g_signal_connect_data(GMPC_CONNECTION(object),"status_changed",(GCallback)(func),(data),(destroy_data),(GConnectFlags)(flags))
#endif /* __GNUC__ && !__STRICT_ANSI__ */


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
