/* Generated by GOB (v2.0.14)   (do not edit directly) */

#ifndef __GMPC_CONNECTION_PRIVATE_H__
#define __GMPC_CONNECTION_PRIVATE_H__

#include "gmpc-connection.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct _GmpcConnectionPrivate {
#line 9 "connection.gob"
	MpdObj * mi;
#line 16 "gmpc-connection-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
