/* Generated by GOB (v2.0.14)   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 14

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "gmpc-connection.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */
/* self casting macros */
#define SELF(x) GMPC_CONNECTION(x)
#define SELF_CONST(x) GMPC_CONNECTION_CONST(x)
#define IS_SELF(x) GMPC_IS_CONNECTION(x)
#define TYPE_SELF GMPC_TYPE_CONNECTION
#define SELF_CLASS(x) GMPC_CONNECTION_CLASS(x)

#define SELF_GET_CLASS(x) GMPC_CONNECTION_GET_CLASS(x)

/* self typedefs */
typedef GmpcConnection Self;
typedef GmpcConnectionClass SelfClass;

/* here are local prototypes */
static void gmpc_connection_init (GmpcConnection * o) G_GNUC_UNUSED;
static void gmpc_connection_class_init (GmpcConnectionClass * c) G_GNUC_UNUSED;
static void ___real_gmpc_connection_connection_changed (GmpcConnection * self, MpdObj * mi, int connect);
static void ___real_gmpc_connection_status_changed (GmpcConnection * self, MpdObj * mi, ChangedStatusType what);

/*
 * Signal connection wrapper macro shortcuts
 */
#define self_connect__connection_changed(object,func,data)	gmpc_connection_connect__connection_changed((object),(func),(data))
#define self_connect_after__connection_changed(object,func,data)	gmpc_connection_connect_after__connection_changed((object),(func),(data))
#define self_connect_data__connection_changed(object,func,data,destroy_data,flags)	gmpc_connection_connect_data__connection_changed((object),(func),(data),(destroy_data),(flags))
#define self_connect__status_changed(object,func,data)	gmpc_connection_connect__status_changed((object),(func),(data))
#define self_connect_after__status_changed(object,func,data)	gmpc_connection_connect_after__status_changed((object),(func),(data))
#define self_connect_data__status_changed(object,func,data,destroy_data,flags)	gmpc_connection_connect_data__status_changed((object),(func),(data),(destroy_data),(flags))

typedef void  (*___Sig1) (GmpcConnection *, gpointer , gint , gpointer);

static void
___marshal_Sig1 (GClosure *closure,
	GValue *return_value G_GNUC_UNUSED,
	guint n_param_values,
	const GValue *param_values,
	gpointer invocation_hint G_GNUC_UNUSED,
	gpointer marshal_data)
{
	register ___Sig1 callback;
	register GCClosure *cc = (GCClosure*) closure;
	register gpointer data1, data2;

	g_return_if_fail (n_param_values == 3);

	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = g_value_peek_pointer (param_values + 0);
	} else {
		data1 = g_value_peek_pointer (param_values + 0);
		data2 = closure->data;
	}

	callback = (___Sig1) (marshal_data != NULL ? marshal_data : cc->callback);

	callback ((GmpcConnection *)data1,
		(gpointer ) g_value_get_pointer (param_values + 1),
		(gint ) g_value_get_int (param_values + 2),
		data2);
}


enum {
	CONNECTION_CHANGED_SIGNAL,
	STATUS_CHANGED_SIGNAL,
	LAST_SIGNAL
};

static guint object_signals[LAST_SIGNAL] = {0};

/* pointer to the class of our parent */
static GObjectClass *parent_class = NULL;

/* Short form macros */
#define self_connection_changed gmpc_connection_connection_changed
#define self_status_changed gmpc_connection_status_changed
#define self_new gmpc_connection_new
GType
gmpc_connection_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (GmpcConnectionClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) gmpc_connection_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (GmpcConnection),
			0 /* n_preallocs */,
			(GInstanceInitFunc) gmpc_connection_init,
			NULL
		};

		type = g_type_register_static (G_TYPE_OBJECT, "GmpcConnection", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((GmpcConnection *)g_object_new(gmpc_connection_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static GmpcConnection * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static GmpcConnection *
GET_NEW_VARG (const char *first, ...)
{
	GmpcConnection *ret;
	va_list ap;
	va_start (ap, first);
	ret = (GmpcConnection *)g_object_new_valist (gmpc_connection_get_type (), first, ap);
	va_end (ap);
	return ret;
}

static void 
gmpc_connection_init (GmpcConnection * o G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Gmpc:Connection::init"
}
#undef __GOB_FUNCTION__
static void 
gmpc_connection_class_init (GmpcConnectionClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Gmpc:Connection::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	parent_class = g_type_class_ref (G_TYPE_OBJECT);

	object_signals[CONNECTION_CHANGED_SIGNAL] =
		g_signal_new ("connection_changed",
			G_TYPE_FROM_CLASS (g_object_class),
			(GSignalFlags)(G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION),
			G_STRUCT_OFFSET (GmpcConnectionClass, connection_changed),
			NULL, NULL,
			___marshal_Sig1,
			G_TYPE_NONE, 2,
			G_TYPE_POINTER,
			G_TYPE_INT);
	if ___GOB_UNLIKELY(sizeof(MpdObj * ) != sizeof(gpointer ) || sizeof(int ) != sizeof(gint ) || parent_class == NULL /* avoid warning */) {
		g_error("connection.gob line 11: Type mismatch of \"connection_changed\" signal signature");
	}
	object_signals[STATUS_CHANGED_SIGNAL] =
		g_signal_new ("status_changed",
			G_TYPE_FROM_CLASS (g_object_class),
			(GSignalFlags)(G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION),
			G_STRUCT_OFFSET (GmpcConnectionClass, status_changed),
			NULL, NULL,
			___marshal_Sig1,
			G_TYPE_NONE, 2,
			G_TYPE_POINTER,
			G_TYPE_INT);
	if ___GOB_UNLIKELY(sizeof(MpdObj * ) != sizeof(gpointer ) || sizeof(ChangedStatusType ) != sizeof(gint ) || parent_class == NULL /* avoid warning */) {
		g_error("connection.gob line 17: Type mismatch of \"status_changed\" signal signature");
	}

#line 11 "connection.gob"
	c->connection_changed = ___real_gmpc_connection_connection_changed;
#line 17 "connection.gob"
	c->status_changed = ___real_gmpc_connection_status_changed;
#line 187 "gmpc-connection.c"
}
#undef __GOB_FUNCTION__



#line 11 "connection.gob"
void 
gmpc_connection_connection_changed (GmpcConnection * self, MpdObj * mi, int connect)
#line 196 "gmpc-connection.c"
{
	GValue ___param_values[3];
	GValue ___return_val;

memset (&___return_val, 0, sizeof (___return_val));
memset (&___param_values, 0, sizeof (___param_values));

#line 11 "connection.gob"
	g_return_if_fail (self != NULL);
#line 11 "connection.gob"
	g_return_if_fail (GMPC_IS_CONNECTION (self));
#line 208 "gmpc-connection.c"

	___param_values[0].g_type = 0;
	g_value_init (&___param_values[0], G_TYPE_FROM_INSTANCE (self));
	g_value_set_instance (&___param_values[0], (gpointer) self);

	___param_values[1].g_type = 0;
	g_value_init (&___param_values[1], G_TYPE_POINTER);
	g_value_set_pointer (&___param_values[1], (gpointer ) mi);

	___param_values[2].g_type = 0;
	g_value_init (&___param_values[2], G_TYPE_INT);
	g_value_set_int (&___param_values[2], (gint ) connect);

	g_signal_emitv (___param_values,
		object_signals[CONNECTION_CHANGED_SIGNAL],
		0 /* detail */,
		&___return_val);

	g_value_unset (&___param_values[0]);
	g_value_unset (&___param_values[1]);
	g_value_unset (&___param_values[2]);
}
#line 11 "connection.gob"
static void 
___real_gmpc_connection_connection_changed (GmpcConnection * self G_GNUC_UNUSED, MpdObj * mi, int connect)
#line 234 "gmpc-connection.c"
{
#define __GOB_FUNCTION__ "Gmpc:Connection::connection_changed"
{
#line 14 "connection.gob"
	
		debug_printf(DEBUG_INFO, "Connection Changed fired\n");
	}}
#line 242 "gmpc-connection.c"
#undef __GOB_FUNCTION__

#line 17 "connection.gob"
void 
gmpc_connection_status_changed (GmpcConnection * self, MpdObj * mi, ChangedStatusType what)
#line 248 "gmpc-connection.c"
{
	GValue ___param_values[3];
	GValue ___return_val;

memset (&___return_val, 0, sizeof (___return_val));
memset (&___param_values, 0, sizeof (___param_values));

#line 17 "connection.gob"
	g_return_if_fail (self != NULL);
#line 17 "connection.gob"
	g_return_if_fail (GMPC_IS_CONNECTION (self));
#line 260 "gmpc-connection.c"

	___param_values[0].g_type = 0;
	g_value_init (&___param_values[0], G_TYPE_FROM_INSTANCE (self));
	g_value_set_instance (&___param_values[0], (gpointer) self);

	___param_values[1].g_type = 0;
	g_value_init (&___param_values[1], G_TYPE_POINTER);
	g_value_set_pointer (&___param_values[1], (gpointer ) mi);

	___param_values[2].g_type = 0;
	g_value_init (&___param_values[2], G_TYPE_INT);
	g_value_set_int (&___param_values[2], (gint ) what);

	g_signal_emitv (___param_values,
		object_signals[STATUS_CHANGED_SIGNAL],
		0 /* detail */,
		&___return_val);

	g_value_unset (&___param_values[0]);
	g_value_unset (&___param_values[1]);
	g_value_unset (&___param_values[2]);
}
#line 17 "connection.gob"
static void 
___real_gmpc_connection_status_changed (GmpcConnection * self G_GNUC_UNUSED, MpdObj * mi, ChangedStatusType what)
#line 286 "gmpc-connection.c"
{
#define __GOB_FUNCTION__ "Gmpc:Connection::status_changed"
{
#line 20 "connection.gob"
	
		debug_printf(DEBUG_INFO, "Status Changed fired\n");
	}}
#line 294 "gmpc-connection.c"
#undef __GOB_FUNCTION__

#line 24 "connection.gob"
GObject * 
gmpc_connection_new (void)
#line 300 "gmpc-connection.c"
{
#define __GOB_FUNCTION__ "Gmpc:Connection::new"
{
#line 27 "connection.gob"
	
		return (GObject *)GET_NEW;
	}}
#line 308 "gmpc-connection.c"
#undef __GOB_FUNCTION__
