/* Generated by GOB (v2.0.14)   (do not edit directly) */

#ifndef __GMPC_METAIMAGE_PRIVATE_H__
#define __GMPC_METAIMAGE_PRIVATE_H__

#include "gmpc-metaimage.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct _GmpcMetaImagePrivate {
#line 12 "cover-image.gob"
	gulong status_signal;
#line 29 "cover-image.gob"
	GtkWidget * image;
#line 18 "gmpc-metaimage-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
